services:
  postgres:
    image: postgres:latest
    env_file: .env
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    depends_on:
      - postgres
    env_file: .env
